---
- hosts: all
  strategy: free
  become: yes
  become_method: sudo
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: 
 
    - name: Create a Tomcat User
      user:
        name: tomcat
 
    - name: Create a Tomcat Group
      group:
        name: tomcat
 
    - name: Install JAVA
      apt:
        name: default-jdk
        state: present
 
 
    - name: Create a Tomcat Directory
      file:
        path: /var/lib/tomcat8
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
 
    - name: download & unarchive tomcat8
      unarchive:
        src: http://apache.cbox.biz/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
        dest: /var/lib/tomcat8
        remote_src: yes
        extra_opts: [--strip-components=1]
 
    - name: Change ownership of tomcat directory
      file:
        path: /var/lib/tomcat8
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
 
    - name: Copy Tomcat service from local to remote
      copy:
        src: files/tomcat.service.txt
        dest: /etc/systemd/system/tomcat.service
        mode: 0755
    
    - name: Copy Tomcat users from local to remote
      copy:
        src: files/tomcat-users.xml
        dest: /var/lib/tomcat8/conf/tomcat-users.xml
        mode: 0755

    - name: Modify Manager config 
      copy:
        src: files/context.xml
        dest: /var/lib/tomcat8/webapps/manager/META-INF/context.xml
        mode: 0755

    - name: Modify Host-manager config 
      copy:
        src: files/context.xml
        dest: /var/lib/tomcat8/webapps/host-manager/META-INF/context.xml
        mode: 0755
    
    - name: Start and Enable Tomcat 8 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true

     
